basePath: /
definitions:
  handlers.LanguageTagBody:
    properties:
      iso_code_1:
        type: string
      iso_code_2:
        type: string
      name:
        type: string
    type: object
  handlers.LanguageTagGetAllResponse:
    properties:
      id:
        type: integer
      iso_code_1:
        type: string
      iso_code_2:
        type: string
      name:
        type: string
      variants_count:
        type: integer
    type: object
  handlers.LanguageTagResponse:
    properties:
      id:
        type: integer
      iso_code_1:
        type: string
      iso_code_2:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for UURL Admin service.
  title: UURL Admin API
  version: "1.0"
paths:
  /language:
    get:
      description: Retrieve all language tags with their associated variants
      produces:
      - application/json
      responses:
        "200":
          description: List of Language Tags with variants
          schema:
            items:
              $ref: '#/definitions/handlers.LanguageTagGetAllResponse'
            type: array
        "500":
          description: Failed to get language tags
          schema:
            type: string
      summary: Get all language tags
      tags:
      - LanguageTags
    post:
      consumes:
      - application/json
      description: Insert a new language tag and its associated variants
      parameters:
      - description: Language Tag with Variants
        in: body
        name: languageTag
        required: true
        schema:
          $ref: '#/definitions/handlers.LanguageTagBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created Language Tag with variants
          schema:
            $ref: '#/definitions/handlers.LanguageTagResponse'
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Failed to insert language tag or variants
          schema:
            type: string
      summary: Create a new language tag
      tags:
      - LanguageTags
  /language/{id}:
    get:
      description: Retrieve a specific language tag and its variants by ID
      parameters:
      - description: Language Tag ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Language Tag with variants
          schema:
            $ref: '#/definitions/handlers.LanguageTagResponse'
        "404":
          description: Language tag not found
          schema:
            type: string
        "500":
          description: Failed to get variants
          schema:
            type: string
      summary: Get language tag by ID
      tags:
      - LanguageTags
swagger: "2.0"
