// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: language_tag_variants.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getPaginatedVariantsWithFilter = `-- name: GetPaginatedVariantsWithFilter :many
SELECT id, language_tag_id, created_at, updated_at, variant_tag, description, is_iana_language_sub_tag, instances_on_domains_count FROM language_tag_variants
WHERE language_tag_id = $3::integer
ORDER BY id
LIMIT $1 OFFSET $2
`

type GetPaginatedVariantsWithFilterParams struct {
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
	LanguageTagID int32 `json:"language_tag_id"`
}

func (q *Queries) GetPaginatedVariantsWithFilter(ctx context.Context, arg GetPaginatedVariantsWithFilterParams) ([]LanguageTagVariant, error) {
	rows, err := q.db.QueryContext(ctx, getPaginatedVariantsWithFilter, arg.Limit, arg.Offset, arg.LanguageTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LanguageTagVariant{}
	for rows.Next() {
		var i LanguageTagVariant
		if err := rows.Scan(
			&i.ID,
			&i.LanguageTagID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VariantTag,
			&i.Description,
			&i.IsIanaLanguageSubTag,
			&i.InstancesOnDomainsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaginatedVariantsWithoutFilter = `-- name: GetPaginatedVariantsWithoutFilter :many
SELECT id, language_tag_id, created_at, updated_at, variant_tag, description, is_iana_language_sub_tag, instances_on_domains_count FROM language_tag_variants
ORDER BY id
LIMIT $1 OFFSET $2
`

type GetPaginatedVariantsWithoutFilterParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetPaginatedVariantsWithoutFilter(ctx context.Context, arg GetPaginatedVariantsWithoutFilterParams) ([]LanguageTagVariant, error) {
	rows, err := q.db.QueryContext(ctx, getPaginatedVariantsWithoutFilter, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LanguageTagVariant{}
	for rows.Next() {
		var i LanguageTagVariant
		if err := rows.Scan(
			&i.ID,
			&i.LanguageTagID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VariantTag,
			&i.Description,
			&i.IsIanaLanguageSubTag,
			&i.InstancesOnDomainsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariantCount = `-- name: GetVariantCount :one
SELECT count(id) FROM language_tag_variants WHERE language_tag_id = $1
`

func (q *Queries) GetVariantCount(ctx context.Context, languageTagID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVariantCount, languageTagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVariantsByLanguageTagID = `-- name: GetVariantsByLanguageTagID :many
SELECT id, created_at, updated_at, variant_tag, description, is_iana_language_sub_tag, instances_on_domains_count
FROM language_tag_variants WHERE language_tag_id = $1
`

type GetVariantsByLanguageTagIDRow struct {
	ID                      int32          `json:"id"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	VariantTag              string         `json:"variant_tag"`
	Description             sql.NullString `json:"description"`
	IsIanaLanguageSubTag    bool           `json:"is_iana_language_sub_tag"`
	InstancesOnDomainsCount int32          `json:"instances_on_domains_count"`
}

func (q *Queries) GetVariantsByLanguageTagID(ctx context.Context, languageTagID sql.NullInt32) ([]GetVariantsByLanguageTagIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getVariantsByLanguageTagID, languageTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVariantsByLanguageTagIDRow{}
	for rows.Next() {
		var i GetVariantsByLanguageTagIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VariantTag,
			&i.Description,
			&i.IsIanaLanguageSubTag,
			&i.InstancesOnDomainsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVariant = `-- name: InsertVariant :exec
INSERT INTO language_tag_variants (language_tag_id, variant_tag, description, is_iana_language_sub_tag, instances_on_domains_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertVariantParams struct {
	LanguageTagID           sql.NullInt32  `json:"language_tag_id"`
	VariantTag              string         `json:"variant_tag"`
	Description             sql.NullString `json:"description"`
	IsIanaLanguageSubTag    bool           `json:"is_iana_language_sub_tag"`
	InstancesOnDomainsCount int32          `json:"instances_on_domains_count"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

func (q *Queries) InsertVariant(ctx context.Context, arg InsertVariantParams) error {
	_, err := q.db.ExecContext(ctx, insertVariant,
		arg.LanguageTagID,
		arg.VariantTag,
		arg.Description,
		arg.IsIanaLanguageSubTag,
		arg.InstancesOnDomainsCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateVariant = `-- name: UpdateVariant :exec
UPDATE language_tag_variants set language_tag_id = $2, variant_tag = $3, description = $4, is_iana_language_sub_tag = $5, updated_at = $6 where id = $1
`

type UpdateVariantParams struct {
	ID                   int32          `json:"id"`
	LanguageTagID        sql.NullInt32  `json:"language_tag_id"`
	VariantTag           string         `json:"variant_tag"`
	Description          sql.NullString `json:"description"`
	IsIanaLanguageSubTag bool           `json:"is_iana_language_sub_tag"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) error {
	_, err := q.db.ExecContext(ctx, updateVariant,
		arg.ID,
		arg.LanguageTagID,
		arg.VariantTag,
		arg.Description,
		arg.IsIanaLanguageSubTag,
		arg.UpdatedAt,
	)
	return err
}
