// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Country struct {
	ID                int32          `json:"id"`
	Name              string         `json:"name"`
	OfficialStateName sql.NullString `json:"official_state_name"`
	Tld               string         `json:"tld"`
	Iso31662A1        string         `json:"iso3166_2_a1"`
	Iso31662A3        string         `json:"iso3166_2_a3"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type CountryLanguage struct {
	CountryID  int32 `json:"country_id"`
	LanguageID int32 `json:"language_id"`
}

type Language struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Iso6391 string `json:"iso_639_1"`
	Iso6392 string `json:"iso_639_2"`
}

type Variant struct {
	ID          int32          `json:"id"`
	LanguageID  sql.NullInt32  `json:"language_id"`
	CountryID   sql.NullInt32  `json:"country_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	VariantTag  string         `json:"variant_tag"`
	Description sql.NullString `json:"description"`
}
