// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type LanguageTag struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	IsoCode1 string `json:"iso_code_1"`
	IsoCode2 string `json:"iso_code_2"`
}

type LanguageTagVariant struct {
	ID                      int32          `json:"id"`
	LanguageTagID           sql.NullInt32  `json:"language_tag_id"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	VariantTag              string         `json:"variant_tag"`
	Description             sql.NullString `json:"description"`
	IsIanaLanguageSubTag    bool           `json:"is_iana_language_sub_tag"`
	InstancesOnDomainsCount int32          `json:"instances_on_domains_count"`
}
