// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetAllCountries(ctx context.Context) ([]GetAllCountriesRow, error)
	GetAllLanguageTags(ctx context.Context) ([]Language, error)
	GetCountryById(ctx context.Context, id int32) (GetCountryByIdRow, error)
	GetFilteredCountry(ctx context.Context, dollar_1 []int32) ([]GetFilteredCountryRow, error)
	GetLanguageTagByID(ctx context.Context, id int32) (Language, error)
	GetPaginatedVariantsWithFilter(ctx context.Context, arg GetPaginatedVariantsWithFilterParams) ([]Variant, error)
	GetPaginatedVariantsWithoutFilter(ctx context.Context, arg GetPaginatedVariantsWithoutFilterParams) ([]Variant, error)
	GetVariantCount(ctx context.Context, languageID sql.NullInt32) (int64, error)
	GetVariantsByLanguageTagID(ctx context.Context, languageID sql.NullInt32) ([]GetVariantsByLanguageTagIDRow, error)
	InsertCountry(ctx context.Context, arg InsertCountryParams) (int32, error)
	InsertLanguageTag(ctx context.Context, arg InsertLanguageTagParams) (int32, error)
	InsertVariant(ctx context.Context, arg InsertVariantParams) error
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) error
}

var _ Querier = (*Queries)(nil)
