// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetAllLanguageTags(ctx context.Context) ([]LanguageTag, error)
	GetLanguageTagByID(ctx context.Context, id int32) (LanguageTag, error)
	GetVariantsByLanguageTagID(ctx context.Context, languageTagID sql.NullInt32) ([]GetVariantsByLanguageTagIDRow, error)
	InsertLanguageTag(ctx context.Context, arg InsertLanguageTagParams) (int32, error)
	InsertVariant(ctx context.Context, arg InsertVariantParams) error
}

var _ Querier = (*Queries)(nil)
